version: 0.2

env:
  variables:
    ECR_REPO: "648908580279.dkr.ecr.ap-south-1.amazonaws.com/devenvmanual"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REPO
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPO:$IMAGE_TAG
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"flaskapp","imageUri":"%s"}]' $ECR_REPO:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
