version: 0.2

env:
  variables:
    ECR_REPO: 648908580279.dkr.ecr.ap-south-1.amazonaws.com/devenvmanual
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - echo $ECR_REPO
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker push $ECR_REPO:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
