version: 0.2

env:
  variables:
    ECR_REPO: "648908580279.dkr.ecr.ap-south-1.amazonaws.com/devenvmanual"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Logging into ECR..."
      - aws --version
      - aws sts get-caller-identity
      - export LOGIN_PASSWORD=$(aws ecr get-login-password --region ap-south-1)
      - echo "$LOGIN_PASSWORD" | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPO:$IMAGE_TAG
      - echo "Build and push complete."

artifacts:
  files:
    - '**/*'
